### ISSUE TITLE
LibStag.lib file not getting generated

### ISSUE THREAD

**Issue by entcat** [bbenligiray/stag#28]
I am building the current version in Windows 10 using cmake 3.22.2 and also using Visual Studio 2019, the .dll, .pdb files are getting generated in debug and release but .lib files are not getting generated. Is the .cmake file correctly written because i tried building multiple times but in vain. Any help would be highly appreciated. 
Thanks.

**Comment by bbenligiray** [comment]
You can either compile a library dynamically (which will output .dll files) or statically (which will output .lib files). Check out https://www.google.com/search?q=dll+lib+site%3Astackoverflow.com

I remember building EDLines (the line detection library used in STag) in both ways and using them in other projects, but it's been too long and I don't remember it well enough to be of any help. I'm closing this issue because it's not specific to this codebase in any way.
